Add `ConstOsmosisTestPool` and implement `lock_tokens` for `OsmosisTestRobot`
apollodao/cw-it pull request #20
Opened 2023-03-04 19:12 UTC by apollo-pacman

2023-03-04 21:23 UTC, apollo-sturdy requested changes

2023-03-04 21:23 UTC, apollo-sturdy commented on src/osmosis/robot.rs
> +}
Might be worth adding a test too. E.g.
```rust
#[test]
fn test_is_osmosis_lp_token() {
    // Success cases
    assert!(is_osmosis_lp_token("gamm/pool/1"));
    assert!(is_osmosis_lp_token("gamm/pool/12"));
    assert!(is_osmosis_lp_token("gamm/pool/123"));
    assert!(is_osmosis_lp_token("gamm/pool/1234"));

    // Failure cases
    assert!(!is_osmosis_lp_token(""));
    assert!(!is_osmosis_lp_token("gamm"));
    assert!(!is_osmosis_lp_token("gamm/"));
    assert!(!is_osmosis_lp_token("gamm/pool"));
    assert!(!is_osmosis_lp_token("gamm/pool/"));
    assert!(!is_osmosis_lp_token("gamm/pool/1/"));
    assert!(!is_osmosis_lp_token("gamm/pool/1/2"));
    assert!(!is_osmosis_lp_token("gamm/pool/1/2/3"));
    assert!(!is_osmosis_lp_token("test/pool/1"));
    assert!(!is_osmosis_lp_token("gamm/test/1"));
    assert!(!is_osmosis_lp_token("gamm/pool/test"));
}
```

2023-03-05 18:01 UTC, apollo-pacman commented on src/osmosis/robot.rs
> +}
fixed

2023-03-05 18:15 UTC, apollo-pacman commented on src/osmosis/robot.rs
> +    fn lock_tokens(&self, signer: &SigningAccount, coin: Coin, duration: i64) -> &Self {
the message takes an i64 yes. but its a bit wierd. a u64 might not be castable to an i64 but i'll change it to an u32 instead which should be good

2023-03-05 18:15 UTC, apollo-pacman commented on src/const_coin.rs
> +#[derive(Debug, Clone, PartialEq, Eq)]
done

2023-03-05 18:17 UTC, merged